[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PMFRG_xyz = "785b06fc-d355-4226-8a27-57b35e93bce2"
Recorder = "c5f2e5b5-9010-42ac-aa93-6ef73b86c405"
SpinFRGLattices = "053fb7f8-31b7-4f68-aef8-4452b415dd8c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
